// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_AIVOICEAGENT_H_
#define _BEHAVIAC_AIVOICEAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class aiVoiceAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE aiVoiceAgent
///<<< END WRITING YOUR CODE
{
public:
    aiVoiceAgent();
    virtual ~aiVoiceAgent();

    BEHAVIAC_DECLARE_AGENTTYPE(aiVoiceAgent, behaviac::Agent)

public:
    void SayHello();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
