// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_GENERATED_BEHAVIORS_H_
#define _BEHAVIAC_GENERATED_BEHAVIORS_H_

#include "../types/behaviac_types.h"

namespace behaviac
{
// Source file: aiVoiceBehaviorBT

class Action_bt_aiVoiceBehaviorBT_node0 : public Action
{
public:
    BEHAVIAC_DECLARE_DYNAMIC_TYPE(Action_bt_aiVoiceBehaviorBT_node0, Action);
    Action_bt_aiVoiceBehaviorBT_node0()
    {
    }
protected:
    virtual EBTStatus update_impl(Agent* pAgent, EBTStatus childStatus)
    {
        BEHAVIAC_UNUSED_VAR(pAgent);
        BEHAVIAC_UNUSED_VAR(childStatus);
        ((aiVoiceAgent*)pAgent)->SayHello();
        return BT_SUCCESS;
    }
};

class bt_aiVoiceBehaviorBT
{
public:
    static bool Create(BehaviorTree* pBT)
    {
        pBT->SetClassNameString("BehaviorTree");
        pBT->SetId((uint16_t)-1);
        pBT->SetName("aiVoiceBehaviorBT");
        pBT->SetIsFSM(false);
#if !BEHAVIAC_RELEASE
        pBT->SetAgentType("aiVoiceAgent");
#endif
        // children
        {
            Action_bt_aiVoiceBehaviorBT_node0* node0 = BEHAVIAC_NEW Action_bt_aiVoiceBehaviorBT_node0;
            node0->SetClassNameString("Action");
            node0->SetId(0);
#if !BEHAVIAC_RELEASE
            node0->SetAgentType("aiVoiceAgent");
#endif
            pBT->AddChild(node0);
            pBT->SetHasEvents(pBT->HasEvents() | node0->HasEvents());
        }
        return true;
    }
};

}
#endif // _BEHAVIAC_GENERATED_BEHAVIORS_H_
